import { useState } from "react";
import { Alert,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View } from "react-native";
import { router } from "expo-router";
import { supabase } from "@/lib/supabase";
export default function Login(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[loading,setLoading]=useState(false);
 async function signIn(){if(!email.trim()||!password)return Alert.alert("Chave 10","Informe e-mail e senha.");setLoading(true);const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setLoading(false);if(error)return Alert.alert("Não foi possível entrar",error.message);router.replace("/(tabs)")}
 return <KeyboardAvoidingView style={s.container} behavior={Platform.OS==="ios"?"padding":undefined}><View style={s.logoRow}><View style={s.badge}><Text style={s.badgeText}>10</Text></View><Text style={s.logo}>CHAVE 10</Text></View><Text style={s.subtitle}>Gestão de Oficina</Text><View style={s.card}><Text style={s.title}>Entrar</Text><TextInput style={s.input} placeholder="E-mail" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Senha" secureTextEntry value={password} onChangeText={setPassword}/><Pressable style={s.button} onPress={signIn} disabled={loading}><Text style={s.buttonText}>{loading?"Entrando...":"Entrar no Chave 10"}</Text></Pressable></View></KeyboardAvoidingView>
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:"#172033",padding:24,justifyContent:"center"},logoRow:{flexDirection:"row",alignItems:"center",justifyContent:"center"},badge:{backgroundColor:"#f59b32",borderRadius:10,paddingHorizontal:12,paddingVertical:8,marginRight:9},badgeText:{color:"#fff",fontWeight:"800",fontSize:20},logo:{color:"#fff",fontSize:24,fontWeight:"800"},subtitle:{color:"#aeb7c7",textAlign:"center",marginTop:8,marginBottom:28},card:{backgroundColor:"#fff",borderRadius:18,padding:22},title:{fontSize:24,fontWeight:"800",color:"#172033",marginBottom:16},input:{borderWidth:1,borderColor:"#d7dce3",borderRadius:10,padding:14,marginBottom:12,fontSize:16},button:{backgroundColor:"#f59b32",borderRadius:10,padding:15,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"800",fontSize:16}});
