"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Plan={id:string;name:string;slug:string;price_monthly:number};
type Office={id:string;name:string;created_at:string;subscription_status:string;trial_ends_at:string|null;plan_id:string|null;plan_name:string|null;plan_price_monthly:number|null};
const label=(s:string)=>({trial:"Teste",active:"Ativa",past_due:"Pendente",suspended:"Suspensa",canceled:"Cancelada"}[s]||s);
export default function AdminPage(){
 const router=useRouter(); const [loading,setLoading]=useState(true); const [authorized,setAuthorized]=useState(false); const [offices,setOffices]=useState<Office[]>([]); const [plans,setPlans]=useState<Plan[]>([]); const [error,setError]=useState(""); const [saving,setSaving]=useState("");
 async function loadData(){const [{data:o,error:oe},{data:p,error:pe}]=await Promise.all([supabase.rpc("admin_list_offices"),supabase.from("plans").select("id,name,slug,price_monthly").eq("is_active",true).order("price_monthly")]);if(oe||pe){setError("Não foi possível carregar os dados.");return}setOffices((o||[]) as Office[]);setPlans((p||[]) as Plan[])}
 useEffect(()=>{(async()=>{const {data:u}=await supabase.auth.getUser();if(!u.user){router.replace("/login?next=/admin");return}const {data:p,error:e}=await supabase.from("user_profiles").select("role,is_active").eq("user_id",u.user.id).maybeSingle();if(e||!p||p.role!=="admin"||!p.is_active){setError("Acesso restrito ao administrador do Chave 10.");setLoading(false);return}setAuthorized(true);await loadData();setLoading(false)})()},[router]);
 async function action(id:string,fn:string,args:Record<string,unknown>={}){setSaving(id);setError("");const {error:e}=await supabase.rpc(fn,args);if(e)setError(e.message||"Não foi possível atualizar a oficina.");else await loadData();setSaving("")}
 if(loading)return <main style={page}><section style={card}>Carregando área administrativa...</section></main>;
 if(!authorized)return <main style={page}><section style={card}><div style={brand}>CHAVE <span>10</span></div><h1>Área administrativa</h1><p style={muted}>{error}</p><button onClick={()=>router.replace("/")} style={button}>Voltar</button></section></main>;
 return <main style={page}><section style={{...card,maxWidth:1150}}><div style={brand}>CHAVE <span>10</span></div><h1 style={{margin:"18px 0 6px"}}>Painel Admin</h1><p style={muted}>Controle de oficinas, planos e acessos</p>{error&&<div style={alert}>{error}</div>}<div style={stats}><b>{offices.length}</b><span>oficinas cadastradas</span></div><h2 style={{margin:"28px 0 10px"}}>Planos</h2><div style={planGrid}>{plans.map(p=><div key={p.id} style={planCard}><b>{p.name}</b><div style={{fontSize:22,marginTop:6}}>R$ {Number(p.price_monthly).toFixed(2).replace(".",",")}/mês</div></div>)}</div><h2 style={{margin:"28px 0 10px"}}>Oficinas</h2>{offices.map(o=><div key={o.id} style={row}><div style={{minWidth:220}}><b>{o.name}</b><div style={small}>Plano: {o.plan_name||"Sem plano"} {o.plan_price_monthly!=null&&`• R$ ${Number(o.plan_price_monthly).toFixed(2).replace(".",",")}`}</div><div style={small}>Status: {label(o.subscription_status)}</div>{o.trial_ends_at&&<div style={small}>Teste até: {new Date(o.trial_ends_at).toLocaleDateString("pt-BR")}</div>}</div><div style={controls}><select value={o.plan_id||""} disabled={saving===o.id} onChange={e=>e.target.value&&action(o.id,"admin_set_office_plan",{p_office_id:o.id,p_plan_id:e.target.value})} style={select}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{o.subscription_status!=="active"&&<button disabled={saving===o.id} onClick={()=>action(o.id,"admin_set_office_status",{p_office_id:o.id,p_status:"active"})} style={button}>Ativar</button>}{o.subscription_status!=="suspended"&&<button disabled={saving===o.id} onClick={()=>action(o.id,"admin_set_office_status",{p_office_id:o.id,p_status:"suspended"})} style={secondary}>Suspender</button>}{o.subscription_status!=="canceled"&&<button disabled={saving===o.id} onClick={()=>action(o.id,"admin_set_office_status",{p_office_id:o.id,p_status:"canceled"})} style={danger}>Cancelar</button>}<button disabled={saving===o.id} onClick={()=>action(o.id,"admin_extend_trial",{p_office_id:o.id,p_days:14})} style={outline}>+14 dias</button>{saving===o.id&&<span style={small}>Salvando...</span>}</div></div>)}<button onClick={()=>router.replace("/")} style={{...button,marginTop:24}}>Voltar ao sistema</button></section></main>}
const page:React.CSSProperties={minHeight:"100vh",background:"#f3f5f8",padding:24,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"Arial,sans-serif",color:"#172033"};const card:React.CSSProperties={width:"100%",background:"white",borderRadius:16,padding:30,boxShadow:"0 12px 40px rgba(23,32,51,.12)"};const brand:React.CSSProperties={fontWeight:900,fontSize:26};const button:React.CSSProperties={border:0,borderRadius:8,padding:"10px 13px",background:"#f59b32",color:"white",fontWeight:800,cursor:"pointer"};const secondary:React.CSSProperties={...button,background:"#172033"};const danger:React.CSSProperties={...button,background:"#b42318"};const outline:React.CSSProperties={...button,background:"white",color:"#172033",border:"1px solid #ccd3dd"};const muted:React.CSSProperties={color:"#687386"};const small:React.CSSProperties={fontSize:12,color:"#687386",marginTop:4};const stats:React.CSSProperties={marginTop:20,padding:18,borderRadius:10,background:"#f5f7fa",display:"flex",alignItems:"baseline",gap:8};const row:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,padding:"16px 0",borderBottom:"1px solid #e5e8ed"};const controls:React.CSSProperties={display:"flex",alignItems:"center",gap:8,flexWrap:"wrap",justifyContent:"flex-end"};const select:React.CSSProperties={border:"1px solid #d8dde5",borderRadius:8,padding:"9px 10px",background:"white",color:"#172033"};const planGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12};const planCard:React.CSSProperties={border:"1px solid #e5e8ed",borderRadius:10,padding:16,background:"#fafbfc"};const alert:React.CSSProperties={marginTop:16,padding:12,borderRadius:8,background:"#fff1f0",color:"#a33"};