"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Client={id:string;name:string;phone:string|null};
type Vehicle={id:string;client_id:string;plate:string|null;brand:string|null;model:string|null;year:number|null;mileage:number|null};
type Order={id:string;number:string;client_id:string;vehicle_id:string|null;description:string|null;status:string;labor:number;parts:number;discount:number;total:number;notes:string|null;created_at:string};
const brl=(n:number)=>`R$ ${Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`;
const date=(v:string)=>new Date(v).toLocaleDateString("pt-BR");

export default function Historico(){
 const[clients,setClients]=useState<Client[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[orders,setOrders]=useState<Order[]>([]),[selected,setSelected]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:of,error:oe}=await supabase.from("offices").select("id").limit(1);if(oe||!of?.[0]){setError(oe?.message||"Nenhuma oficina encontrada.");setLoading(false);return}const id=of[0].id;const[c,v,o]=await Promise.all([supabase.from("clients").select("id,name,phone").eq("office_id",id).order("name"),supabase.from("vehicles").select("id,client_id,plate,brand,model,year,mileage").eq("office_id",id).order("created_at",{ascending:false}),supabase.from("service_orders").select("id,number,client_id,vehicle_id,description,status,labor,parts,discount,total,notes,created_at").eq("office_id",id).order("created_at",{ascending:false})]);const e=c.error||v.error||o.error;if(e)setError(e.message);setClients(c.data||[]);setVehicles(v.data||[]);setOrders(o.data||[]);setLoading(false)})()},[]);
 const vehicle=vehicles.find(v=>v.id===selected);const client=clients.find(c=>c.id===vehicle?.client_id);const serviceHistory=useMemo(()=>selected?orders.filter(o=>o.vehicle_id===selected):[],[selected,orders]);const total=serviceHistory.reduce((s,o)=>s+Number(o.total||0),0);
 if(loading)return <main style={{padding:40,fontFamily:"Arial"}}>Carregando histórico...</main>;
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:30,fontFamily:"Arial,sans-serif",color:"#172033"}}><div style={{maxWidth:1100,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><div><small style={{color:"#687386"}}>CHAVE 10 · GESTÃO DE OFICINA</small><h1 style={{margin:"5px 0"}}>Histórico do veículo</h1><p style={{color:"#687386"}}>Consulte todas as Ordens de Serviço realizadas em cada veículo.</p></div><button onClick={()=>window.history.back()} style={secondary}>← Voltar</button></div>{error&&<div style={err}>{error}</div>}<section style={card}><label style={{fontWeight:700}}>Selecione o veículo</label><select value={selected} onChange={e=>setSelected(e.target.value)} style={input}><option value="">Selecione...</option>{vehicles.map(v=><option key={v.id} value={v.id}>{[v.brand,v.model].filter(Boolean).join(" ")||"Veículo"}{v.plate?` · ${v.plate}`:""} — {clients.find(c=>c.id===v.client_id)?.name||""}</option>)}</select></section>{vehicle&&<><section style={{...card,marginTop:16}}><h2 style={{marginTop:0}}>{[vehicle.brand,vehicle.model].filter(Boolean).join(" ")||"Veículo"}</h2><div style={grid}><div><b>Placa</b><br/>{vehicle.plate||"—"}</div><div><b>Proprietário</b><br/>{client?.name||"—"}</div><div><b>Ano</b><br/>{vehicle.year||"—"}</div><div><b>KM cadastrado</b><br/>{vehicle.mileage?.toLocaleString("pt-BR")||"—"}</div><div><b>Visitas</b><br/>{serviceHistory.length}</div><div><b>Total em serviços</b><br/>{brl(total)}</div></div></section><section style={{...card,marginTop:16,overflowX:"auto"}}><h2 style={{marginTop:0}}>Histórico de serviços</h2>{serviceHistory.length?<table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Data","OS","Serviço","Status","Total"].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{serviceHistory.map(o=><tr key={o.id}><td style={td}>{date(o.created_at)}</td><td style={td}><b>{o.number}</b></td><td style={td}>{o.description||"—"}</td><td style={td}>{o.status}</td><td style={td}>{brl(o.total)}</td></tr>)}</tbody></table>:<p style={{color:"#687386"}}>Nenhuma Ordem de Serviço registrada para este veículo.</p>}</section></>}</div></main>;
}
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:12,marginTop:8,border:"1px solid #d7dce3",borderRadius:8};const card:React.CSSProperties={background:"white",padding:20,borderRadius:12,border:"1px solid #e5e7eb"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:18};const th:React.CSSProperties={textAlign:"left",padding:10,borderBottom:"1px solid #e5e7eb"};const td:React.CSSProperties={padding:10,borderBottom:"1px solid #f0f0f0"};const secondary:React.CSSProperties={background:"white",border:"1px solid #ccd2da",borderRadius:7,padding:"10px 15px",fontWeight:700};const err:React.CSSProperties={padding:12,marginBottom:15,background:"#fff0f0",border:"1px solid #efb4b4",borderRadius:8,color:"#9b2226"};
