import {useEffect,useState} from "react";
import {ActivityIndicator,FlatList,Modal,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {supabase} from "@/lib/supabase"; import {getOfficeId} from "@/lib/office";
type P={id:string;description:string;quantity:number;unit_price:number};
const money=(v:string)=>Number(String(v||"").replace(/\./g,"").replace(",","."))||0;
const brl=(n:number)=>`R$ ${Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`;
export default function Estoque(){
 const[items,setItems]=useState<P[]>([]),[loading,setLoading]=useState(true),[desc,setDesc]=useState(""),[qty,setQty]=useState(""),[price,setPrice]=useState(""),[mode,setMode]=useState<"entrada"|"saida">("entrada"),[selected,setSelected]=useState(""),[picker,setPicker]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);try{const id=await getOfficeId();const{data,error:e}=await supabase.from("products").select("id,description,quantity,unit_price").eq("office_id",id).order("description");if(e)throw e;setItems(data||[])}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar estoque")}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 async function save(){setError("");try{const id=await getOfficeId();const q=money(qty);if(q<=0)throw new Error("Informe uma quantidade.");if(mode==="entrada"){if(!desc.trim())throw new Error("Informe o produto.");const pr=money(price);if(pr<0)throw new Error("Preço inválido.");const{data:p,error:fe}=await supabase.from("products").select("id,quantity").eq("office_id",id).ilike("description",desc.trim()).maybeSingle();if(fe)throw fe;let pid="";if(p){const{error:e}=await supabase.from("products").update({quantity:Number(p.quantity)+q,unit_price:pr,updated_at:new Date().toISOString()}).eq("id",p.id);if(e)throw e;pid=p.id}else{const{data:n,error:e}=await supabase.from("products").insert({office_id:id,description:desc.trim(),quantity:q,unit_price:pr,code:"P-"+Date.now().toString(36).toUpperCase()}).select("id").single();if(e||!n)throw e||new Error("Não foi possível cadastrar o produto.");pid=n.id}const{error:me}=await supabase.from("inventory_movements").insert({office_id:id,product_id:pid,type:"entrada",quantity:q,unit_price:pr,description:"Entrada de estoque"});if(me)throw me}else{const p=items.find(x=>x.id===selected);if(!p)throw new Error("Selecione o produto.");if(q>Number(p.quantity))throw new Error("Estoque insuficiente.");const{error:e}=await supabase.from("products").update({quantity:Number(p.quantity)-q,updated_at:new Date().toISOString()}).eq("id",p.id);if(e)throw e;const{error:me}=await supabase.from("inventory_movements").insert({office_id:id,product_id:p.id,type:"saida",quantity:q,unit_price:Number(p.unit_price||0),description:"Saída de estoque"});if(me)throw me}setDesc("");setQty("");setPrice("");setSelected("");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível registrar")}}
 if(loading)return <View style={s.center}><ActivityIndicator color="#f59b32"/></View>;
 return <View style={s.screen}><FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={s.content} ListHeaderComponent={<><Text style={s.title}>Estoque</Text><Text style={s.sub}>Entradas, saídas e produtos.</Text><View style={s.tabs}><Pressable onPress={()=>setMode("entrada")} style={[s.tab,mode==="entrada"&&s.active]}><Text>Entrada</Text></Pressable><Pressable onPress={()=>setMode("saida")} style={[s.tab,mode==="saida"&&s.active]}><Text>Saída</Text></Pressable></View>{mode==="entrada"?<><TextInput style={s.input} placeholder="Produto" value={desc} onChangeText={setDesc}/><TextInput style={s.input} placeholder="Quantidade" keyboardType="decimal-pad" value={qty} onChangeText={setQty}/><TextInput style={s.input} placeholder="Preço unitário" keyboardType="decimal-pad" value={price} onChangeText={setPrice}/></>:<><Pressable style={s.select} onPress={()=>setPicker(true)}><Text style={selected?s.selectedText:s.placeholder}>{items.find(x=>x.id===selected)?.description||"Selecionar produto"}</Text></Pressable><TextInput style={s.input} placeholder="Quantidade" keyboardType="decimal-pad" value={qty} onChangeText={setQty}/></>}<Pressable style={s.btn} onPress={save}><Text style={s.btnText}>Registrar {mode}</Text></Pressable>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.section}>Produtos</Text></>} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.description}</Text><Text style={s.muted}>Quantidade: {item.quantity} · {brl(item.unit_price)}</Text></View>}/>
 <Modal visible={picker} transparent animationType="slide" onRequestClose={()=>setPicker(false)}><View style={s.overlay}><View style={s.picker}><Text style={s.pickerTitle}>Selecionar produto</Text><FlatList data={items} keyExtractor={x=>x.id} renderItem={({item})=><Pressable style={s.row} onPress={()=>{setSelected(item.id);setPicker(false)}}><Text style={s.name}>{item.description}</Text><Text style={s.muted}>Estoque: {item.quantity} · {brl(item.unit_price)}</Text></Pressable>}/><Pressable style={s.cancel} onPress={()=>setPicker(false)}><Text>Cancelar</Text></Pressable></View></View></Modal>
 </View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#f5f7fa"},content:{padding:18},center:{flex:1,justifyContent:"center",alignItems:"center"},title:{fontSize:26,fontWeight:"800",color:"#172033"},sub:{color:"#687386",marginBottom:12},tabs:{flexDirection:"row",gap:8,marginVertical:8},tab:{padding:10,borderRadius:8,backgroundColor:"#fff"},active:{backgroundColor:"#eef2f6"},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#d7dce3",borderRadius:9,padding:12,marginTop:8},select:{backgroundColor:"#fff",borderWidth:1,borderColor:"#d7dce3",borderRadius:9,padding:13,marginTop:8},selectedText:{color:"#172033"},placeholder:{color:"#9aa3b2"},btn:{backgroundColor:"#f59b32",padding:13,borderRadius:9,alignItems:"center",marginTop:10},btnText:{color:"#fff",fontWeight:"800"},error:{color:"#9b2226",marginTop:8},section:{fontSize:18,fontWeight:"800",marginTop:20,marginBottom:10},card:{backgroundColor:"#fff",padding:15,borderRadius:12,marginBottom:9},name:{fontWeight:"800",color:"#172033"},muted:{color:"#687386",marginTop:4},overlay:{flex:1,backgroundColor:"rgba(0,0,0,.5)",justifyContent:"flex-end"},picker:{backgroundColor:"#fff",borderTopLeftRadius:18,borderTopRightRadius:18,maxHeight:"75%",padding:18},pickerTitle:{fontSize:20,fontWeight:"900",marginBottom:10},row:{paddingVertical:13,borderBottomWidth:1,borderBottomColor:"#eef0f3"},cancel:{padding:14,alignItems:"center",backgroundColor:"#eef2f6",borderRadius:10,marginTop:10}});
