import {useEffect,useMemo,useState} from "react"; import {ActivityIndicator,FlatList,Pressable,StyleSheet,Text,View} from "react-native"; import {supabase} from "@/lib/supabase"; import {getOfficeId} from "@/lib/office";
type F={id:string;type:string;amount:number;description:string|null;category:string|null;service_order_id:string|null;created_at:string};
const brl=(n:number)=>`R$ ${Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`;
export default function Financeiro(){const[data,setData]=useState<F[]>([]),[loading,setLoading]=useState(true),[period,setPeriod]=useState<"Hoje"|"Semana"|"Mês">("Mês"),[error,setError]=useState("");
 async function load(){setLoading(true);try{const id=await getOfficeId();const{data,error}=await supabase.from("financial_entries").select("id,type,amount,description,category,service_order_id,created_at").eq("office_id",id).order("created_at",{ascending:false}).limit(500);if(error)throw error;setData(data||[])}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar financeiro")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const now=new Date();let start=new Date(now);if(period==="Hoje")start.setHours(0,0,0,0);if(period==="Semana"){start.setDate(now.getDate()-6);start.setHours(0,0,0,0)}if(period==="Mês")start=new Date(now.getFullYear(),now.getMonth(),1);return data.filter(x=>new Date(x.created_at)>=start)},[data,period]);
 const entradas=filtered.filter(x=>x.type==="entrada").reduce((s,x)=>s+Number(x.amount||0),0),saidas=filtered.filter(x=>x.type==="saida").reduce((s,x)=>s+Number(x.amount||0),0),faturamento=filtered.filter(x=>x.type==="entrada"&&(!!x.service_order_id||(x.category||"").toLowerCase()==="ordem de serviço")).reduce((s,x)=>s+Number(x.amount||0),0);
 if(loading)return <View style={s.center}><ActivityIndicator color="#f59b32"/></View>;return <FlatList style={s.screen} contentContainerStyle={s.content} data={filtered} keyExtractor={x=>x.id} ListHeaderComponent={<><Text style={s.title}>Financeiro</Text><View style={s.tabs}>{(["Hoje","Semana","Mês"] as const).map(p=><Pressable key={p} onPress={()=>setPeriod(p)} style={[s.tab,period===p&&s.active]}><Text>{p}</Text></Pressable>)}</View><View style={s.grid}><View style={s.metric}><Text style={s.label}>Entradas</Text><Text style={s.value}>{brl(entradas)}</Text></View><View style={s.metric}><Text style={s.label}>Saídas</Text><Text style={s.value}>{brl(saidas)}</Text></View><View style={s.metric}><Text style={s.label}>Saldo</Text><Text style={s.value}>{brl(entradas-saidas)}</Text></View><View style={s.metric}><Text style={s.label}>Faturamento em OS</Text><Text style={s.value}>{brl(faturamento)}</Text></View><View style={s.metric}><Text style={s.label}>Resultado</Text><Text style={s.value}>{brl(entradas-saidas)}</Text></View></View>{error?<Text style={s.error}>{error}</Text>:null}</>} renderItem={({item})=><View style={s.card}><Text style={s.type}>{item.type==="entrada"?"Entrada":"Saída"}</Text><Text>{item.description||"Lançamento"}</Text><Text style={s.amount}>{brl(item.amount)}</Text><Text style={s.date}>{new Date(item.created_at).toLocaleDateString("pt-BR")}</Text></View>}/>};
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#f5f7fa"},content:{padding:18},center:{flex:1,alignItems:"center",justifyContent:"center"},title:{fontSize:26,fontWeight:"800",color:"#172033",marginBottom:14},tabs:{flexDirection:"row",gap:8,marginBottom:12},tab:{padding:10,borderRadius:8,backgroundColor:"#fff"},active:{backgroundColor:"#eef2f6"},grid:{gap:8},metric:{backgroundColor:"#172033",padding:14,borderRadius:12},label:{color:"#cbd2dc"},value:{color:"#fff",fontSize:18,fontWeight:"800",marginTop:3},card:{backgroundColor:"#fff",padding:15,borderRadius:12,marginTop:9},type:{fontWeight:"800",color:"#f59b32"},amount:{fontWeight:"900",marginTop:5},date:{color:"#687386",marginTop:3},error:{color:"#9b2226",paddingVertical:8}});
