import {useEffect,useState} from "react";
import {ActivityIndicator,Alert,FlatList,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {supabase} from "@/lib/supabase"; import {getOfficeId} from "@/lib/office";
type O={id:string;number:string;client_id:string;description:string|null;status:string;total:number};
type C={id:string;name:string};
const money=(v:string)=>Number(String(v||"").replace(/\\./g,"").replace(",","."))||0;
export default function OS(){
 const[loading,setLoading]=useState(true),[orders,setOrders]=useState<O[]>([]),[clients,setClients]=useState<C[]>([]),[modal,setModal]=useState(false),[client,setClient]=useState(""),[service,setService]=useState(""),[labor,setLabor]=useState(""),[parts,setParts]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);try{const id=await getOfficeId();const[o,c]=await Promise.all([supabase.from("service_orders").select("id,number,client_id,description,status,total").eq("office_id",id).order("created_at",{ascending:false}),supabase.from("clients").select("id,name").eq("office_id",id).order("name")]);if(o.error)throw o.error;if(c.error)throw c.error;setOrders(o.data||[]);setClients(c.data||[])}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar OS")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(){if(!client||!service.trim()){setError("Informe cliente e serviço.");return}try{const id=await getOfficeId();const number=`OS-${Date.now().toString().slice(-6)}`;const{error:e}=await supabase.rpc("create_service_order_with_parts",{p_client_id:client,p_vehicle_id:null,p_number:number,p_description:service.trim(),p_labor:money(labor),p_parts:money(parts),p_discount:0,p_notes:null,p_items:[]});if(e)throw e;setModal(false);setClient("");setService("");setLabor("");setParts("");await load();Alert.alert("OS criada",number)}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar a OS")}}
 async function status(id:string,status:string){const{error:e}=await supabase.from("service_orders").update({status,updated_at:new Date().toISOString(),...(status==="Concluída"?{completed_at:new Date().toISOString()}:{}),...(status==="Entregue"?{delivered_at:new Date().toISOString()}: {})}).eq("id",id);if(e)setError(e.message);else load()}
 if(loading)return <View style={s.center}><ActivityIndicator color="#f59b32"/></View>;
 return <View style={s.screen}><FlatList data={orders} keyExtractor={x=>x.id} contentContainerStyle={s.content} ListHeaderComponent={<View style={s.header}><View><Text style={s.title}>Ordens de serviço</Text><Text style={s.sub}>Criação e acompanhamento das OS.</Text></View><Pressable style={s.btn} onPress={()=>setModal(true)}><Text style={s.btnText}>+ Nova</Text></Pressable></View>} ListEmptyComponent={<Text style={s.empty}>Nenhuma OS cadastrada.</Text>} renderItem={({item})=><View style={s.card}><Text style={s.num}>{item.number}</Text><Text style={s.client}>{clients.find(c=>c.id===item.client_id)?.name||"Cliente"}</Text><Text style={s.service}>{item.description||"Serviço"}</Text><Text style={s.total}>R$ {Number(item.total||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</Text><Text style={s.status}>Status: {item.status}</Text><View style={s.actions}>{["Aberta","Em andamento","Concluída","Entregue","Cancelada"].map(v=><Pressable key={v} onPress={()=>status(item.id,v)} style={[s.statusBtn,item.status===v&&s.active]}><Text style={item.status===v?s.activeText:s.statusText}>{v}</Text></Pressable>)}</View></View>}/>{error?<Text style={s.error}>{error}</Text>:null}
 {modal&&<View style={s.overlay}><View style={s.modal}><Text style={s.modalTitle}>Nova OS</Text><Text style={s.label}>Cliente</Text><FlatList horizontal data={clients} keyExtractor={x=>x.id} renderItem={({item})=><Pressable onPress={()=>setClient(item.id)} style={[s.chip,client===item.id&&s.chipActive]}><Text>{item.name}</Text></Pressable>}/><TextInput style={s.input} placeholder="Serviço" value={service} onChangeText={setService}/><TextInput style={s.input} placeholder="Mão de obra (R$)" keyboardType="decimal-pad" value={labor} onChangeText={setLabor}/><TextInput style={s.input} placeholder="Peças (R$)" keyboardType="decimal-pad" value={parts} onChangeText={setParts}/><Pressable style={s.btn} onPress={save}><Text style={s.btnText}>Salvar OS</Text></Pressable><Pressable onPress={()=>setModal(false)} style={s.cancel}><Text>Cancelar</Text></Pressable></View></View>}</View>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#f5f7fa"},content:{padding:18},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:16},title:{fontSize:25,fontWeight:"800",color:"#172033"},sub:{color:"#687386"},btn:{backgroundColor:"#f59b32",padding:12,borderRadius:10},btnText:{color:"#fff",fontWeight:"800"},card:{backgroundColor:"#fff",padding:16,borderRadius:14,marginBottom:10,borderWidth:1,borderColor:"#e5e7eb"},num:{fontWeight:"800"},client:{fontSize:17,fontWeight:"800",marginTop:7},service:{marginTop:7,color:"#344054"},total:{fontSize:17,fontWeight:"900",marginTop:9},status:{color:"#687386",marginTop:5},actions:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:10},statusBtn:{borderWidth:1,borderColor:"#d7dce3",padding:7,borderRadius:7},active:{backgroundColor:"#172033"},statusText:{fontSize:10},activeText:{fontSize:10,color:"#fff"},empty:{color:"#687386",padding:20},error:{color:"#9b2226",padding:12},overlay:{position:"absolute",inset:0,backgroundColor:"rgba(0,0,0,.5)",justifyContent:"center",padding:18},modal:{backgroundColor:"#fff",borderRadius:16,padding:20},modalTitle:{fontSize:22,fontWeight:"900",color:"#172033"},label:{fontWeight:"800",marginTop:12,marginBottom:6},chip:{padding:10,borderWidth:1,borderColor:"#ddd",borderRadius:20,marginRight:7},chipActive:{backgroundColor:"#eef2f6"},input:{borderWidth:1,borderColor:"#d7dce3",borderRadius:9,padding:13,marginTop:10},cancel:{padding:14,alignItems:"center"}});
