"use client";

const MERCADO_PAGO_URL="https://mpago.la/18fhBWP";

const modules=[
["👥","Clientes","Cadastro completo e histórico de atendimento."],
["🚗","Veículos","Veículos vinculados ao cliente e histórico."],
["📄","Orçamentos em PDF","Orçamentos profissionais prontos para compartilhar."],
["🔧","Ordens de Serviço","Controle do serviço da abertura à entrega."],
["📦","Estoque","Entradas, saídas, peças e saldo em estoque."],
["💰","Financeiro","Lançamentos financeiros gerados pelas OS."],
["📲","WhatsApp","Compartilhe orçamentos em PDF pelo WhatsApp."],
["📊","Dashboard","Visão geral da operação da oficina."],
["🧾","Histórico","Consulte serviços e informações dos veículos."],
["☁️","Acesso online","Use o sistema pela internet, sem instalação."],
["📱","Responsivo","Celular, tablet, notebook e computador."],
["🔐","Acesso protegido","Login e áreas internas separadas da página de vendas."],
];

function DashboardMock({kind="desktop"}:{kind?:string}){
 const cls=kind==="phone"?"device phone":kind==="tablet"?"device tablet":kind==="laptop"?"device laptop":"device desktop";
 return <div className={cls}>
  <div className="mockTop"><b>CHAVE <i>10</i></b><span>Visão Geral</span></div>
  <div className="mockBody"><div className="mockSide"><b>Dashboard</b><span>Clientes</span><span>Veículos</span><span>Orçamentos</span><span>Ordens de Serviço</span><span>Estoque</span><span>Financeiro</span><span>Relatórios</span></div>
  <div className="mockMain"><div className="stats"><div>OS em andamento<strong>12</strong></div><div>Orçamentos<strong>8</strong></div><div>Faturamento<strong>R$ 12.450</strong></div><div>Clientes<strong>156</strong></div></div><div className="mockChart"><b>Serviços por mês</b><div className="bars"><em/><em/><em/><em/><em/><em/><em/></div></div><div className="mockTable"><b>Ordens de Serviço recentes</b><span/><span/><span/></div></div></div>
 </div>
}

export default function Home(){
 return <main className="sales">
 <style>{`
*{box-sizing:border-box}.sales{font-family:Arial,Helvetica,sans-serif;color:#172033;background:#fff;line-height:1.45}.sales a{text-decoration:none}
.nav{height:74px;padding:0 4%;display:flex;align-items:center;justify-content:space-between;background:#fff;border-bottom:1px solid #e7ebf1;position:sticky;top:0;z-index:50}.logo{font-size:27px;font-weight:900;color:#172033}.logo i{font-style:normal;background:#f59b32;color:#fff;padding:7px 11px;border-radius:9px;margin-left:5px}.logo small{display:block;color:#748096;font-size:9px;letter-spacing:1.4px;margin-top:1px}.navlinks{display:flex;gap:27px;font-size:13px;font-weight:700}.btn{display:inline-flex;align-items:center;justify-content:center;border-radius:9px;padding:13px 21px;font-weight:800}.light{background:#eef1f5;color:#172033}.orange{background:#f59b32;color:#fff;box-shadow:0 7px 18px #f59b3238}
.hero{background:linear-gradient(120deg,#101b30,#182d4b);color:#fff;padding:45px 4% 30px;overflow:hidden}.heroGrid{max-width:1250px;margin:auto;display:grid;grid-template-columns:.85fr 1.3fr;gap:30px;align-items:center}.eyebrow{color:#f59b32;font-size:13px;font-weight:900;letter-spacing:1.5px}.hero h1{font-size:49px;line-height:1.02;margin:12px 0 18px;letter-spacing:-2px}.hero h1 em{font-style:normal;color:#f59b32}.hero p{font-size:17px;color:#dce4ee;max-width:520px}.actions{display:flex;gap:12px;margin:25px 0}.checks{display:grid;gap:9px;color:#e0e6ef;font-size:13px}.checks span:before{content:"✓";display:inline-grid;place-items:center;width:21px;height:21px;background:#f59b32;border-radius:50%;margin-right:8px;font-weight:900}
.heroVisual{display:flex;align-items:center;justify-content:center}.heroVisual .desktop{width:100%;max-width:760px}.device{background:#f2f5f8;border:7px solid #fff;border-radius:15px;box-shadow:0 20px 45px #0007;overflow:hidden}.mockTop{height:42px;background:#172238;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 13px;font-size:12px}.mockTop i{font-style:normal;background:#f59b32;border-radius:5px;padding:3px 5px}.mockBody{display:flex;background:#f7f8fb;min-height:240px}.mockSide{width:110px;background:#172238;color:#dce3ec;padding:10px;display:flex;flex-direction:column;gap:8px;font-size:9px}.mockSide b{background:#30405b;color:#fff;padding:6px;border-radius:5px}.mockMain{flex:1;padding:10px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.stats div,.mockChart,.mockTable{background:#fff;border:1px solid #dfe4eb;border-radius:6px;padding:7px;font-size:7px;color:#6b7689}.stats strong{display:block;color:#172033;font-size:13px;margin-top:3px}.mockChart{margin-top:7px;height:75px}.bars{display:flex;align-items:end;gap:5px;height:42px;margin-top:5px}.bars em{display:block;flex:1;background:#f59b32;border-radius:3px 3px 0 0}.bars em:nth-child(1){height:35%}.bars em:nth-child(2){height:60%}.bars em:nth-child(3){height:48%}.bars em:nth-child(4){height:80%}.bars em:nth-child(5){height:65%}.bars em:nth-child(6){height:90%}.bars em:nth-child(7){height:72%}.mockTable{margin-top:7px;height:58px}.mockTable span{display:block;height:4px;background:#e2e7ef;margin:6px 0;border-radius:4px}
.featureTitle{text-align:center;padding:55px 20px 25px}.featureTitle h2{font-size:31px;margin:6px 0}.featureTitle p{color:#68758a}.moduleGrid{max-width:1200px;margin:0 auto;padding:15px 4% 60px;display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.module{padding:19px 10px;text-align:center;border-right:1px solid #e4e8ee}.moduleIcon{font-size:27px;margin-bottom:8px}.module strong{display:block}.module p{font-size:11px;color:#69758a;margin:7px 0}
.dark{background:#111d31;color:#fff;padding:70px 4%}.darkGrid{max-width:1200px;margin:auto;display:grid;grid-template-columns:.85fr 1.15fr;gap:50px;align-items:center}.dark h2,.access h2{font-size:38px;line-height:1.08;margin:8px 0 15px}.dark p{color:#d6deea}.tickList{list-style:none;padding:0;color:#e2e8f0}.tickList li{margin:11px 0}.tickList li:before{content:"✓";background:#f59b32;border-radius:50%;padding:2px 6px;margin-right:8px}
.access{padding:70px 4%;background:#f8fafc}.accessInner{max-width:1200px;margin:auto;text-align:center}.access p{color:#69758a}.deviceCards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:35px}.deviceCard{background:#fff;border:1px solid #e2e7ee;border-radius:12px;padding:16px;text-align:left;box-shadow:0 10px 25px #17203310;display:flex;gap:12px;align-items:center}.deviceCardVisual{height:105px;width:75px;background:#17243a;border:5px solid #e6ebf2;border-radius:12px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:10px;text-align:center}.deviceCard:nth-child(2) .deviceCardVisual{width:80px;height:105px}.deviceCard:nth-child(3) .deviceCardVisual{width:115px;height:75px}.deviceCard:nth-child(4) .deviceCardVisual{width:125px;height:78px}.deviceCard b{color:#f59b32}.deviceCard h3{margin:0}.deviceCard ul{padding:0;list-style:none;font-size:11px;color:#68758a}.deviceCard li:before{content:"✓ ";color:#f59b32;font-weight:900}
.planBand{background:#111d31;color:#fff;padding:38px 4%}.planInner{max-width:1200px;margin:auto;display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:35px;align-items:center}.price{font-size:45px;font-weight:900;color:#f59b32}.planBand ul{list-style:none;padding:0}.planBand li{margin:8px 0}.planBand li:before{content:"✓";color:#45c879;font-weight:900;margin-right:8px}
.footer{padding:35px 4%;text-align:center}.footer h2{font-size:29px}
.wa{position:fixed;right:20px;bottom:20px;width:58px;height:58px;background:#18c66a;color:#fff;border-radius:50%;display:grid;place-items:center;font-size:27px;z-index:80;box-shadow:0 8px 25px #0004}
@media(max-width:900px){.heroVisual .desktop{width:100%}.navlinks{display:none}.heroGrid,.darkGrid{grid-template-columns:1fr}.hero h1{font-size:39px}.heroDevices{height:320px}.heroDevices .desktop{width:85%}.moduleGrid{grid-template-columns:repeat(3,1fr)}.deviceCards{grid-template-columns:repeat(2,1fr)}.planInner{grid-template-columns:1fr;text-align:center}.actions .btn{flex:1}}
@media(max-width:560px){.nav{padding:10px 14px}.logo{font-size:20px}.nav .btn{padding:10px 12px}.hero{padding:35px 16px 20px}.hero h1{font-size:35px}.hero p{font-size:15px}.heroDevices{height:275px}.heroDevices .laptop{width:42%}.heroDevices .tablet{width:33%}.heroDevices .phone{width:17%}.moduleGrid{grid-template-columns:repeat(2,1fr);padding-left:12px;padding-right:12px}.module{border-right:0}.deviceCards{grid-template-columns:1fr}.dark,.access{padding:50px 18px}.dark h2,.access h2{font-size:31px}}
`}</style>
<header className="nav"><a className="logo" href="/">CHAVE <i>10</i><small>GESTÃO DE OFICINA</small></a><nav className="navlinks"><a href="#funcionalidades">Funcionalidades</a><a href="#como-funciona">Como funciona</a><a href="#planos">Planos</a><a href="#duvidas">Dúvidas</a></nav><div><a className="btn light" href="/login">Entrar</a> <a className="btn orange" href={MERCADO_PAGO_URL}>Começar agora →</a></div></header>
<section className="hero"><div className="heroGrid"><div><div className="eyebrow">SISTEMA COMPLETO DE GESTÃO PARA OFICINAS</div><h1>Sua oficina <em>mais organizada, lucrativa e em um só lugar.</em></h1><p>Controle clientes, veículos, orçamentos, ordens de serviço, estoque e financeiro em um só lugar, com uma interface simples e profissional.</p><div className="actions"><a className="btn orange" href={MERCADO_PAGO_URL}>🚀 Começar agora →</a><a className="btn light" href="#como-funciona">Ver como funciona</a></div><div className="checks"><span>Fácil de usar</span><span>Acesso em qualquer dispositivo</span><span>Gestão simples e profissional</span></div></div><div className="heroVisual"><DashboardMock/></div></div></section>
<section id="funcionalidades"><div className="featureTitle"><div className="eyebrow">FUNCIONALIDADES</div><h2>Tudo que sua oficina precisa, em um só sistema.</h2><p>Ferramentas completas para você organizar, crescer e lucrar mais.</p></div><div className="moduleGrid">{modules.map(([icon,title,desc])=><article className="module" key={title}><div className="moduleIcon">{icon}</div><strong>{title}</strong><p>{desc}</p></article>)}</div></section>
<section id="como-funciona" className="dark"><div className="darkGrid"><div><div className="eyebrow">SISTEMA COMPLETO</div><h2>Mais controle. Menos complicação.</h2><p>O Chave 10 centraliza a operação da oficina em uma interface simples, rápida e profissional.</p><ul className="tickList"><li>Interface simples e intuitiva</li><li>Funciona em qualquer dispositivo</li><li>Dados seguros na nuvem</li><li>Controle de peças e movimentações</li><li>Orçamentos, OS e histórico de veículos</li><li>Financeiro e relatórios</li><li>Suporte em português</li><li>Atualizações constantes</li></ul></div><div><DashboardMock/></div></div></section>
<section className="access"><div className="accessInner"><div className="eyebrow">ACESSO EM QUALQUER DISPOSITIVO</div><h2>Use no celular, tablet, notebook ou computador.</h2><p>O Chave 10 funciona no navegador e se adapta a diferentes tamanhos de tela.</p></div></section>
<section id="planos"/> className="planBand"><div className="planInner"><div><div className="eyebrow">PLANOS ACESSÍVEIS</div><h2 style={{margin:"5px 0"}}>Comece agora por apenas</h2><div className="price">R$ 29,99<span style={{fontSize:18}}>/mês</span></div><p>Sem instalação. Cancele quando quiser.</p></div><ul><li>Todas as funcionalidades</li><li>Suporte em português</li><li>Acesso pelo navegador</li><li>Sem fidelidade</li></ul><div style={{textAlign:"center"}}><a className="btn orange" href={MERCADO_PAGO_URL}>🚀 Quero começar agora →</a><p>Pagamento seguro via Mercado Pago</p></div></div></section>
<section id="duvidas" className="featureTitle"><div className="eyebrow">DÚVIDAS</div><h2>Perguntas frequentes</h2><p>Precisa instalar? Não. O Chave 10 funciona online. Posso usar em mais de um computador? Sim. Como pago? Via Mercado Pago.</p></section>
<footer className="footer"><h2>Pronto para levar sua oficina a um novo nível?</h2><a className="btn orange" href={MERCADO_PAGO_URL}>Começar agora →</a><p>© 2026 Chave 10. Todos os direitos reservados.</p></footer>
<a className="wa" href="https://wa.me/" aria-label="WhatsApp">◔</a>
</main>;
}