"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

export default function LoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false); const [recovery,setRecovery]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user)router.replace("/painel")})},[router]);
 function friendly(message:string){const n=message.toLowerCase();if(n.includes("invalid login credentials"))return "E-mail ou senha incorretos.";if(n.includes("email not confirmed"))return "Seu e-mail ainda não foi confirmado.";if(n.includes("rate limit")||n.includes("too many requests"))return "Limite temporário de envio de e-mails atingido. Aguarde um pouco.";return message}
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");if(!email.trim()||!password){setError("Informe e-mail e senha.");return}if(password.length<8){setError("Use uma senha com pelo menos 8 caracteres.");return}setLoading(true);const {error:e2}=await supabase.auth.signInWithPassword({email:email.trim(),password});setLoading(false);if(e2){setError(friendly(e2.message));return}router.replace("/painel");router.refresh()}
 async function forgot(){setError("");setMessage("");if(!email.trim()){setError("Informe seu e-mail para receber o link de troca de senha.");return}setLoading(true);const {error:e2}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/senha`});setLoading(false);if(e2){setError(friendly(e2.message));return}setMessage("Enviamos um link para seu e-mail. Verifique também a caixa de spam.")}
 return <main style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#f3f5f8",padding:20,fontFamily:"Arial,sans-serif",color:"#172033"}}><section style={{width:"100%",maxWidth:430,background:"white",borderRadius:16,padding:30,boxShadow:"0 12px 40px rgba(23,32,51,.12)"}}><div style={{textAlign:"center",marginBottom:24}}><div style={{fontWeight:900,fontSize:28}}>CHAVE <span style={{background:"#f59b32",color:"white",padding:"4px 8px",borderRadius:7}}>10</span></div><div style={{color:"#687386",marginTop:8}}>Gestão de Oficina</div></div><div style={{background:"#eef1f5",padding:5,borderRadius:9,marginBottom:20,textAlign:"center",fontWeight:700}}>Acesso</div><form onSubmit={submit}><label>E-mail</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" style={input}/><label>Senha</label><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha" style={input}/>{error&&<div style={noticeError}>{error}</div>}{message&&<div style={noticeOk}>{message}</div>}<button disabled={loading} type="submit" style={{width:"100%",marginTop:12,background:"#f59b32",color:"white",border:0,borderRadius:8,padding:13,fontWeight:800,cursor:loading?"wait":"pointer"}}>{loading?"Aguarde...":"Entrar no Chave 10"}</button><button disabled={loading} type="button" onClick={forgot} style={{width:"100%",marginTop:10,background:"white",color:"#172033",border:0,padding:10,fontWeight:700,cursor:loading?"wait":"pointer"}}>Esqueci minha senha</button></form><p style={{fontSize:12,color:"#687386",textAlign:"center",marginTop:20}}>O acesso à criação de oficinas é exclusivo do administrador.</p></section></main>}
const input:React.CSSProperties={width:"100%",padding:12,margin:"6px 0 14px",border:"1px solid #d7dce3",borderRadius:8,boxSizing:"border-box"};const noticeError:React.CSSProperties={marginTop:8,padding:10,borderRadius:7,background:"#fff0f0",border:"1px solid #efb4b4",color:"#9b2226",fontSize:13};const noticeOk:React.CSSProperties={marginTop:8,padding:10,borderRadius:7,background:"#eefbf3",border:"1px solid #b7e1c5",color:"#176b38",fontSize:13};